NetCorePSAV/Controllers/PSAVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.JavaScript;
using Microsoft.AspNetCore.Hosting;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using System.IO;
using System.Linq.Expressions;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GCCorePSAV.Controllers
{

    public class PSAVController : Controller
    {
        // GET: /<controller>/
        Data.clsQuery ConSQL = new Data.clsQuery();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult EPT()
        {
            ViewBag.CRList = ConSQL.EPTSearch();
            return View();
        }
        [HttpPost]
        public IActionResult EPT(string ac1)
        {
            ViewBag.CRList = ConSQL.EPTSearchOne(ac1);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EPT1(object model)
        {
            return View();
        }
        public IActionResult NewEPT()//aqui estamos contestando a un request y le estamos regresando la vista newept con toda la info necesaria
        {
            List<Models.PSAVCrud.CoinsModel> CoinsList = ConSQL.GetCoin(string.Empty);
            List<Models.EPTModel.pricelist> PriceList = ConSQL.GetPriceList();
            List<Models.PSAVCrud.ClientModel.ClientAutoComplete> ClientList = ConSQL.GetAutoClients();
            ViewBag.ClientList = ClientList;
            ViewBag.CoinsList = CoinsList;
            ViewBag.PriceList = PriceList;
            ViewBag.EPTNumberFormat = ConSQL.GetEPTNumber(System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(Request.Cookies["pandoraRules"].ToString())));
            ViewBag.RepVtas = ConSQL.RepVtas();
            ViewBag.Productores = ConSQL.Productores();
            return View(new Models.EPTModel());
        }
        [HttpPost]
        public IActionResult NewEPT(string ac1, Models.EPTModel model, string NewValue, string folio)
        {
            ViewBag.EPTNumberFormat = ConSQL.GetEPTNumber(System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(Request.Cookies["pandoraRules"].ToString())));
            if (NewValue.Equals("0"))
            {
                Models.EPTModel eptM = ConSQL.GetEPTToEdit(folio);
                List<Models.PSAVCrud.CoinsModel> CoinsList = ConSQL.GetCoin(string.Empty);
                List<Models.PSAVCrud.ClientModel.ClientAutoComplete> ClientList = ConSQL.GetAutoClients();
                ViewBag.ClientList = ClientList;
                ViewBag.CoinsList = CoinsList;
                ViewBag.RepVtas = ConSQL.RepVtas();
                ViewBag.Productores = ConSQL.Productores();
                List<Models.PSAVCrud.ClientModel.ClientSearch> Clients = ConSQL.GetClientID(eptM.IDClient);
                for (int i = 0; i < Clients.Count; i++)
                {
                    eptM.DomicilioComercial = Clients[i].Domicilio;
                    eptM.DomicilioFiscal = Clients[i].Fiscal;
                    eptM.IDClient = Clients[i].IDClient;
                    eptM.RazonSocial = Clients[i].Razon;
                    eptM.Phone = Clients[i].Tel;
                    eptM.Mobile = Clients[i].Cel;
                    eptM.Email = Clients[i].Email;
                    eptM.RFC = Clients[i].RFC;
                    eptM.Ext = Clients[i].Ext;
                    eptM.ContactClientName = Clients[i].NombreContacto;
                }
                return View(eptM);
            }
            else
            {
                if (!string.IsNullOrEmpty(ac1))
                {
                    List<Models.PSAVCrud.CoinsModel> CoinsList = ConSQL.GetCoin(string.Empty);
                    List<Models.PSAVCrud.ClientModel.ClientAutoComplete> ClientList = ConSQL.GetAutoClients();
                    List<Models.EPTModel.pricelist> pricelists = ConSQL.GetPriceList();
                    ViewBag.ClientList = ClientList;
                    ViewBag.CoinsList = CoinsList;
                    ViewBag.Pricelist = pricelists;
                    ViewBag.RepVtas = ConSQL.RepVtas();
                    ViewBag.Productores = ConSQL.Productores();
                    List<Models.PSAVCrud.ClientModel.ClientSearch> Clients = ConSQL.GetClient(ac1);
                    Models.EPTModel ept = new Models.EPTModel();
                    for (int i = 0; i < Clients.Count; i++)
                    {
                        ept.DomicilioComercial = Clients[i].Domicilio;
                        ept.DomicilioFiscal = Clients[i].Fiscal;
                        ept.IDClient = Clients[i].IDClient;
                        ept.RazonSocial = Clients[i].Razon;
                        ept.Phone = Clients[i].Tel;
                        ept.Mobile = Clients[i].Cel;
                        ept.Email = Clients[i].Email;
                        ept.RFC = Clients[i].RFC;
                        ept.Ext = Clients[i].Ext;
                        ept.ContactClientName = Clients[i].NombreContacto;
                        ept.IDEmpresa = Clients[i].IDEmpresa;
                    }
                    Response.Cookies.Append("IDC", ept.IDClient, new Microsoft.AspNetCore.Http.CookieOptions { Path = "/", HttpOnly = true });
                    Response.Cookies.Append("IDCE", ept.IDEmpresa, new Microsoft.AspNetCore.Http.CookieOptions { Path = "/", HttpOnly = true });

                    return View(ept);
                }
                else
                {
                    if (ModelState.IsValid)//aqui es donde se da lo de newept
                    {
                        //save model
                        model.IDClient = Request.Cookies["IDC"].ToString();
                        model.IDEmpresa = Request.Cookies["IDCE"].ToString();
                        string IDEvent = ConSQL.InsertEPT(model);
                        ViewBag.EPTM = model;
                        Models.ItemListModel.ItemListEventModel Ilem = new Models.ItemListModel.ItemListEventModel();
                        Ilem.EPTLoad = ViewBag.EPTM;
                        Response.Cookies.Append("IDE", IDEvent, new Microsoft.AspNetCore.Http.CookieOptions { Path = "/", HttpOnly = true });
                        Response.Cookies.Append("EVN", model.EventName, new Microsoft.AspNetCore.Http.CookieOptions { Path = "/", HttpOnly = true });
                        ViewBag.CategoriaList = ConSQL.GetCategoryItemList(1);
                        ViewBag.SubcategoriaList = ConSQL.GetSubcategoryItemList(1);
                        Response.Cookies.Append("PriceL", model.TpListaPrecio, new Microsoft.AspNetCore.Http.CookieOptions { Path = "/", HttpOnly = true });
                        return RedirectToAction("NIL");
                    }
                    else
                    {
                        return View();

                    }
                }
            }
        }
        public static List<NetCorePSAV.Models.ILNewModel.ILGrid> ListGridIL = new List<NetCorePSAV.Models.ILNewModel.ILGrid>();
        public ActionResult ILUd([FromBody]CRUDModel<NetCorePSAV.Models.ILNewModel.ILGrid> myObject2)
        {
            var ord = myObject2.Value;
            NetCorePSAV.Models.ILNewModel.ILGrid val2 = ListGridEIL.Where(or => or.ID == ord.ID).FirstOrDefault();
            val2.Cantidad = ord.Cantidad;
            return Json(myObject2.Value);
        }
        public ActionResult ILU([FromBody]CRUDModel<NetCorePSAV.Models.ILNewModel.ILGrid> myObject2)
        {
            var ord = myObject2.Value;
            NetCorePSAV.Models.ILNewModel.ILGrid val2 = ListGridIL.Where(or => or.ID == ord.ID).FirstOrDefault();
            val2.Cantidad = ord.Cantidad;
            return Json(myObject2.Value);
        }
        public ActionResult ILDe([FromBody]CRUDModel<NetCorePSAV.Models.ILNewModel.ILGrid> value)
        {
            ListGridEIL.Remove(ListGridEIL.Where(or => or.ID == value.Key.ToString()).FirstOrDefault());
            return Json(value);
        }
        public ActionResult ILD([FromBody]CRUDModel<NetCorePSAV.Models.ILNewModel.ILGrid> value)
        {
            ListGridIL.Remove(ListGridIL.Where(or => or.ID == value.Key.ToString()).FirstOrDefault());
            return Json(value);
        }
        [HttpPost]
        public IActionResult NIL(string AddCat,string Item,Models.ItemListModel.ItemListEventModel ILM,string AddOne,string qty)
        {
            ViewBag.datasource2 = WFList;
            if (ServList.Count == 0)
            {
                BindServList(); BindServListWF();
            }
            ViewBag.datasourcedrop = ConSQL.GetListCategory("1");//aquí se estan guardando toda la lista de Categoria
            ViewBag.datasourcedrop2 = ConSQL.GetListCategory("2");//Aquí se estan  guardando toda la lista de workforce

            ViewBag.datasourceM = ServList;
            if (!string.IsNullOrEmpty(AddCat))
            {
                ViewBag.datasourceC = ConSQL.GetCategories();
                ViewBag.datasourceSC = ConSQL.GetSubCategories();
                ViewBag.datasourceI = ConSQL.GetItems();
                if (ListGridIL.Count > 0) {
                    List<NetCorePSAV.Models.ILNewModel.ILGrid> iL = new List<NetCorePSAV.Models.ILNewModel.ILGrid>();
                    iL = ConSQL.GetGrids(Item);
                    iL[0].Cantidad = qty;
                    ListGridIL.Add(iL[0]);                    
                }
                else
                {
                    ListGridIL = ConSQL.GetGrids(Item);
                    ListGridIL[0].Cantidad = qty;
                }
                ViewBag.datasourceILI = ListGridIL;
            }
            string IDITL = "";
            string IDITLWF = "";
            if (!string.IsNullOrEmpty(AddOne))
            {
                switch (AddOne)
                {
                    case "1"://guardar

NetCorePSAV/Views/PSAV/CRatio.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@model EPTModel
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <br />
    <div class="row">
        <h2>Capture Ratio</h2>
    </div>
    <ul class="nav nav-pills">
        <li role="presentation" class="active"><a asp-action="CRatio" asp-controller="PSAV">Consultas</a></li>
        <li role="presentation"><a asp-action="NewCratio" asp-controller="PSAV">Nuevo</a></li>
    </ul>
    <div class="row">
        <form method="post" asp-action="CRatio" asp-controller="PSAV">
            <table border="0">
                <tr><td><input type="text" name="ac1" id="ac1" placeholder="Por Hotel" /></td><td><button type="submit" class="btn btn-default">Buscar</button></td></tr>
            </table>
        </form>
    </div>
    @if (ViewBag.CRList != null)
    {
        <div class="row">
            <div class="col-md-10">
                <table border="0" class="table" width="100%">
                    <thead>
                        <tr>
                            <th>Hotel</th>
                            <th>Location</th>
                            <th>Ciudad</th>
                            <th>DET</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var DetItem in ViewBag.CRList)
                        {
                            <form asp-action="EditCRatio" asp-controller="PSAV" method="post">
                                <tr>
                                    <td>@DetItem.HotelName<input type="hidden" name="IDC" id="IDC" value="@DetItem.IDCratio" /></td>
                                    <td>@DetItem.LocationHotel</td>
                                    <td>@DetItem.CityLoc</td>
                                    <td>@DetItem.DET</td>
                                    <td><button type="submit" class="btn btn-default">Ver Detalle</button></td>
                                </tr>
                            </form>
                        }
                       
                    </tbody>
                </table>
            </div>
        </div>
    }
}

NetCorePSAV/Views/PSAV/EIL.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@using Syncfusion.JavaScript
@using Syncfusion.MVC.EJ
@model SyncPSAV.SalonIL
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <br />
    <div class="container-fluid">
        <form method="post" asp-action="EIL" asp-controller="PSAV">
            <input type="hidden" name="Advance" id="Advance" value="0" />
            <div class="row">
                <h5>Detalle Evento</h5>
                <hr />
                <h6>Datos del Evento</h6>
                <table border="0" class="table" width="100%">
                    <thead>
                        <tr><th>Evento</th></tr>
                    </thead>
                    <tr>
                        <th>Salon</th>
                    </tr>
                    <tr><td><div class="form-group"><input asp-for="Salon" class="form-control" /></div></td></tr>
                    <tr>
                        <th>#Asistentes</th>
                    </tr>
                    <tr><td><div class="form-group"><input asp-for="Asistentes" class="form-control" /></div></td></tr>
                    <tr>
                        <th>Fecha Montaje</th>
                    </tr>
                    <tr><td><div class="form-group"><input asp-for="Montaje" class="form-control" /></div></td></tr>
                    <tr>
                        <th>Horario</th>
                    </tr>
                    <tr><td><div class="form-group"><input asp-for="Horario" class="form-control" /></div></td></tr>
                </table>
                <table border="0">
                    <tr><td><button type="submit" class="btn btn-default">Guardar</button></td></tr>
                </table>
            </div>
        </form>
        <form method="post" asp-action="EditItemList" asp-controller="PSAV">
            <table border="0">
                <tr><td><button type="submit" class="btn btn-default">Regresar</button></td></tr>
            </table>
            <input type="hidden" name="Advance" id="Advance" value="2" />
        </form>
        <div class="row">
            <h4>Agregar Item a lista</h4>
            <form method="post" asp-action="EIL2" asp-controller="PSAV">
                <input type="hidden" value="1" name="config" id="config" />
                <table class="table">
                    <thead>
                        <tr>
                            <th>Clave</th>
                            <th>Cantidad</th>
                            <th>Dias</th>
                            <th>Descripcion</th>
                            <th>PrecioUnit</th>
                            <th>Categoria</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input type="text" class="form-control" name="Clave" id="Clave" /></td>
                            <td><input type="text" class="form-control" name="Cantidad" id="Cantidad" /></td>
                            <td><input type="text" class="form-control" name="Dias" id="Dias" /></td>
                            <td><input type="text" class="form-control" name="Descripcion" id="Descripcion" /></td>
                            <td><input type="text" class="form-control" name="PrecioUnit" id="PrecioUnit" /></td>
                            <td>
                                <select class="form-control" name="Categoria" id="Categoria">
                                    @foreach (var item in ViewBag.datasourcedrop)
                                    {
                                        <option value="@item.Categoria">@item.Categoria</option>
                                    }
                                </select>
                            </td>
                        </tr>
                        <tr><td><button type="submit" class="btn btn-default">Agregar</button></td></tr>
                    </tbody>
                </table>
            </form>
        </div>
        <div class="row">
            <table border="0" class="table" width="100%">
                <thead>
                    <tr><th>Renta de equipo y servicios</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <ej-grid id="FlatGrid" allow-paging="true">
                                <e-datamanager json="(IEnumerable<object>)ViewBag.datasource" update-url="ItemListNormalUpdate" insert-url="ItemListNormalInsert" remove-url="ItemListNormalDelete" adaptor="remoteSaveAdaptor" />
                                <e-edit-settings allow-adding="true" allow-editing="true" allow-deleting="true" edit-mode="@(EditMode.Normal)"></e-edit-settings>
                                <e-toolbar-settings show-toolbar="true" toolbar-items="@(new List<string>() { " add", "edit" , "delete" , "update" , "cancel" })"></e-toolbar-settings>
                                <e-columns>
                                    <e-column field="ID" header-text="ID" is-identity="true" is-primary-key="true" validation-rules='new Dictionary<string, object>() { {"required",true}, {"number",true} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Clave" header-text="Clave" validation-rules='new Dictionary<string, object>() { {"required",true} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Cantidad" header-text="Cantidad" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                    <e-column field="Dias" header-text="Dias" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Descripcion" header-text="Descripcion" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                    <e-column field="PrecioUnit" header-text="PrecioUnit" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Categoria" header-text="Categoria" foreign-key-field="ID" foreign-key-value="Categoria" datasource="ViewBag.datasourcedrop" edit-type="Dropdown"></e-column>
                                </e-columns>
                            </ej-grid>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            <h4>Agregar Item a lista</h4>
            <form method="post" asp-action="EIL2" asp-controller="PSAV">
                <input type="hidden" value="2" name="config" id="config" />
                <table class="table">
                    <thead>
                        <tr>
                            <th>Sección</th>
                            <th>Clave</th>
                            <th>Cantidad</th>
                            <th>Dias</th>
                            <th>Descripcion</th>
                            <th>PrecioUnit</th>
                            <th>Categoria</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><input type="text" class="form-control" name="Seccion" id="Seccion" /></td>
                            <td><input type="text" class="form-control" name="Clave" id="Clave" /></td>
                            <td><input type="text" class="form-control" name="Cantidad" id="Cantidad" /></td>
                            <td><input type="text" class="form-control" name="Dias" id="Dias" /></td>
                            <td><input type="text" class="form-control" name="Descripcion" id="Descripcion" /></td>
                            <td><input type="text" class="form-control" name="PrecioUnit" id="PrecioUnit" /></td>
                            <td>
                                <select class="form-control" name="Categoria" id="Categoria">
                                    @foreach (var item in ViewBag.datasourcedrop2)
                                    {
                                        <option value="@item.Categoria">@item.Categoria</option>
                                    }
                                </select>
                            </td>
                        </tr>
                        <tr><td><button type="submit" class="btn btn-default">Agregar</button></td></tr>
                    </tbody>
                </table>
            </form>
        </div>
        <div class="row">
            <table border="0" class="table" width="100%">
                <thead>
                    <tr><th>Mano de obra</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <ej-grid id="FlatGrid" allow-paging="true">
                                <e-datamanager json="(IEnumerable<object>)ViewBag.datasource" update-url="ItemListWFNormalUpdate" insert-url="ItemListWFNormalInsert" remove-url="ItemListWFNormalDelete" adaptor="remoteSaveAdaptor" />
                                <e-edit-settings allow-adding="false" allow-editing="true" allow-deleting="true" edit-mode="@(EditMode.Normal)"></e-edit-settings>
                                <e-toolbar-settings show-toolbar="true" toolbar-items="@(new List<string>() { "edit", "delete", "update", "cancel" })"></e-toolbar-settings>
                                <e-columns>
                                    <e-column field="ID" header-text="ID" is-identity="true" is-primary-key="true" validation-rules='new Dictionary<string, object>() { {"required",true}, {"number",true} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Seccion" header-text="Seccion" validation-rules='new Dictionary<string, object>() { {"required",true}}' text-align="Right" width="75"></e-column>
                                    <e-column field="Clave" header-text="Clave" validation-rules='new Dictionary<string, object>() { {"required",true} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Cantidad" header-text="Cantidad" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                    <e-column field="Dias" header-text="Dias" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Descripcion" header-text="Descripcion" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                    <e-column field="PrecioUnit" header-text="PrecioUnit" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' text-align="Right" width="75"></e-column>
                                    <e-column field="Categoria" header-text="Categoria" foreign-key-field="Categoria" foreign-key-value="Categoria" datasource="ViewBag.datasourcedrop" edit-type="Dropdown"></e-column>
                                </e-columns>
                            </ej-grid>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
}

NetCorePSAV/Views/PSAV/EditSubrenta.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@using Syncfusion.JavaScript
@using Syncfusion.MVC.EJ
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <br />

    <form method="post" asp-action="EditSubrenta" asp-controller="PSAV">
        <input type="hidden" name="Advance" id="Advance" value="0" />
        <div class="container-fluid">
            <div class="row">
                <table border="0" class="table" width="100%">
                    <thead>
                        <tr><th>Subrenta</th></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <ej-grid id="FlatGrid" allow-paging="true">
                                    <e-datamanager json="(IEnumerable<object>)ViewBag.datasource" update-url="SubRentaNormalUpdate" insert-url="SubRentaNormalInsert" remove-url="SubRentaNormalDelete" adaptor="remoteSaveAdaptor" />
                                    <e-edit-settings allow-adding="true" allow-editing="true" allow-deleting="true" edit-mode="@(EditMode.Dialog)"></e-edit-settings>
                                    <e-toolbar-settings show-toolbar="true" toolbar-items="@(new List<string>() { "add", "edit", "delete", "update", "cancel" })"></e-toolbar-settings>
                                    <e-columns>
                                        <e-column field="ID" header-text="ID" is-identity="true" is-primary-key="true" validation-rules='new Dictionary<string, object>() { {"required",true}, {"number",true} }' text-align="Right" width="75"></e-column>
                                        <e-column field="Categoria" header-text="Categoria" foreign-key-field="ID" foreign-key-value="Categoria" datasource="ViewBag.datasourcedrop" edit-type="Dropdown"></e-column>
                                        <e-column field="Invoice" header-text="#Factura/Cotización" validation-rules='new Dictionary<string, object>() { {"required",true}}' text-align="Right" width="75"></e-column>
                                        <e-column field="Supplier" header-text="Proveedor" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                        <e-column field="Descripcion" header-text="Descripción" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' text-align="Right" width="75"></e-column>
                                        <e-column field="Gastosub" header-text="Gastos subrenta" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                        <e-column field="Ventasub" header-text="Venta subrenta" validation-rules='new Dictionary<string, object>() { {"required",true}, {"minlength",1} }' width="80"></e-column>
                                    </e-columns>
                                </ej-grid>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <table border="0">
            <tr><td><button type="submit" class="btn btn-default">Continuar</button></td></tr>
        </table>
    </form>

}

NetCorePSAV/Views/PSAV/NEPT.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

NetCorePSAV/Views/PSAV/VentaComision.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@using Syncfusion.JavaScript
@using Syncfusion.MVC.EJ
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <br />

    <form method="post" asp-action="VentaComision" asp-controller="PSAV">
        <input type="hidden" name="Advance" id="Advance" value="0" />
        <div class="container-fluid">
            <div class="row">
                <table border="0" class="table" width="100%">
                    <thead>
                        <tr><th>Venta Comisión</th></tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <ej-grid id="FlatGrid" allow-paging="true">
                                    <e-datamanager json="(IEnumerable<object>)ViewBag.datasource" update-url="VtaFeeNormalUpdate" insert-url="VtaFeeNormalInsert" remove-url="VtaFeeNormalDelete" adaptor="remoteSaveAdaptor" />
                                    <e-edit-settings allow-adding="true" allow-editing="true" allow-deleting="true" edit-mode="@(EditMode.Normal)"></e-edit-settings>
                                    <e-toolbar-settings show-toolbar="true" toolbar-items="@(new List<string>() { "add", "edit", "delete", "update", "cancel" })"></e-toolbar-settings>
                                    <e-columns>
                                        <e-column field="ID" header-text="ID" is-identity="true" is-primary-key="true" validation-rules='new Dictionary<string, object>() { {"required",true}, {"number",true} }' text-align="Right" width="75"></e-column>
                                        <e-column field="Category" header-text="Categoría" validation-rules='new Dictionary<string, object>() { {"required",true} }' text-align="Right" width="75"></e-column>
                                        <e-column field="PorcFee" header-text="% Comisión" validation-rules='new Dictionary<string, object>() { {"required",true} }' width="80"></e-column>
                                    </e-columns>
                                </ej-grid>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <table border="0">
            <tr><td><button type="submit" class="btn btn-default">Continuar</button></td></tr>
        </table>
    </form>

}