NetCorePSAV/Models/CaptureRatio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace GCCorePSAV.Models
{
    public class CaptureRatio
    {
        public class CRVResumenModel
        {
            public string IDCratio { get; set; }
            public string HotelName { get; set; }
            public string LocationHotel { get; set; }
            public string CityLoc { get; set; }
            public string DET { get; set; }
            public string Contact { get; set; }
            public string FillFormName { get; set; }
        }
        public class CRVModel
        {
            [Display(Prompt ="Mes / Año MM/YY")]
            [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString ="mm/yy")]
            public string MesOp { get; set; }
            [Display(Prompt ="Hotel")]
            public string HotelName { get; set; }
            [Display(Prompt = "Ciudad")]
            public string City { get; set; }
            [Display(Prompt = "Location Fecha")]
            public string FechaLoc { get; set; }
            [Display(Prompt = "DET")]
            public string DET { get; set; }
            [Display(Prompt = "Contacto DET")]
            public string ContactDET { get; set; }
            [Display(Prompt = "Quien llena")]
            public string NameFillForm { get; set; }
            [Display(Prompt ="Fecha Inicio")]
            [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString = "mm/yy")]
            public string Finicio { get; set; }
            [Display(Prompt = "Fecha Fin")]
            [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString = "mm/yy")]
            public string FFin { get; set; }
            [Display(Prompt ="Nombre del Evento")]
            public string EventName { get; set; }
            [Display(Prompt = "Cliente Final")]
            public string FinalClient { get; set; }
            [Display(Prompt = "Nombre del Contacto")]
            public string ContactName { get; set; }
            [Display(Prompt = "Contacto")]
            public string ContactContact { get; set; }
            [Display(Prompt = "Agencia")]
            public string Agency { get; set; }
            [Display(Prompt = "Tipo de Evento")]
            public string EventType { get; set; }
            [Display(Prompt = "Empresa AV")]
            public string EmpresaAV { get; set; }
            [Display(Prompt = "Responsable PSAV")]
            public string RsponsablePSAV { get; set; }
            [Display(Prompt = "Venta PSAV")]
            public string VentasPSAV { get; set; }
            [Display(Prompt = "Lost Business")]
            public string LB { get; set; }
            [Display(Prompt = "Suma")]
            public string Suma { get; set; }
            [Display(Prompt = "Capture Ratio")]
            public string CRatio { get; set; }
            [Display(Prompt = "Comisión Hotel")]
            public string HotelFee { get; set; }
            [Display(Prompt = "Causa Lost Business")]
            public string LBCause { get; set; }
            [Display(Prompt = "Fecha Siguiente Evento")]
            [DataType(DataType.Date)]
            [DisplayFormat(DataFormatString = "mm/yy")]
            public string NextEventDate { get; set; }
            [Display(Prompt = "Lugar Siguiente Evento")]
            public string NextEventPlace { get; set; }
            public List<CaptureRatio.CRatioList> CRLit { get; set; }
            public string IDCRAtio { get; set; }
        }
        public class CRatioList
        {
            [Display(Prompt = "Fecha Inicio")]
            [DataType(DataType.Date)]
            public string Finicio { get; set; }
            [Display(Prompt = "Fecha Fin")]
            [DataType(DataType.Date)]
            public string FFin { get; set; }
            [Display(Prompt = "Nombre del Evento")]
            public string EventName { get; set; }
            [Display(Prompt = "Cliente Final")]
            public string FinalClient { get; set; }
            [Display(Prompt = "Nombre del Contacto")]
            public string ContactName { get; set; }
            [Display(Prompt = "Contacto")]
            public string ContactContact { get; set; }
            [Display(Prompt = "Agencia")]
            public string Agency { get; set; }
            [Display(Prompt = "Tipo de Evento")]
            public string EventType { get; set; }
            [Display(Prompt = "Empresa AV")]
            public string EmpresaAV { get; set; }
            [Display(Prompt = "Responsable PSAV")]
            public string RsponsablePSAV { get; set; }
            [Display(Prompt = "Venta PSAV")]
            public string VentasPSAV { get; set; }
            [Display(Prompt = "Lost Business")]
            public string LB { get; set; }
            [Display(Prompt = "Suma")]
            public string Suma { get; set; }
            [Display(Prompt = "Capture Ratio")]
            public string CRatio { get; set; }
            [Display(Prompt = "Comisión Hotel")]
            public string HotelFee { get; set; }
            [Display(Prompt = "Causa Lost Business")]
            public string LBCause { get; set; }
            [Display(Prompt = "Fecha Siguiente Evento")]
            public string NextEventDate { get; set; }
            [Display(Prompt = "Lugar Siguiente Evento")]
            public string NextEventPlace { get; set; }
            public string MesFiltro { get; set; }
        }
        public class GetFormatCRL
        {
            public List<CRatioList> CRLL { get; set; }
        }
    }
}

NetCorePSAV/Controllers/CRatioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using System.IO;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Hosting;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NetCorePSAV.Controllers
{
    public class CRatioController : Controller
    {
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly IHostingEnvironment _hostingEnvironment;
        public CRatioController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult ExportCRResult(NetCorePSAV.Models.NCRModel.SearchNCR nCR)
        {
            GCCorePSAV.Data.clsQuery cls = new GCCorePSAV.Data.clsQuery();
            try
            {
                var fileDownloadName = "CaptureRatio.xlsx";
                var reportsFolder = "reports";
                var fileInfo = new FileInfo(Path.Combine(_hostingEnvironment.WebRootPath, reportsFolder, fileDownloadName));
                byte[] ReportArray;
                using (ExcelPackage package = new ExcelPackage(fileInfo))
                {
                    ExcelWorksheet ews = package.Workbook.Worksheets[1];
                    //obtiene lista entera de consulta de ncr
                    List<NetCorePSAV.Models.NCRModel.NCRReporte> reportes = cls.GetCRReportes(nCR);
                    //llena campos de lista ncr
                    for(int i = 0; i < reportes.Count; i++)
                    {
                        ews.Cells["A" + (i + 3).ToString()].Value = reportes[i].nloc;
                        ews.Cells["b" + (i + 3).ToString()].Value = reportes[i].numloc;
                        ews.Cells["c" + (i + 3).ToString()].Value = reportes[i].region;
                        ews.Cells["d" + (i + 3).ToString()].Value = reportes[i].ciudad;
                        ews.Cells["e" + (i + 3).ToString()].Value = cls.GetNameSMDet(reportes[i].det, "1");
                        ews.Cells["f" + (i + 3).ToString()].Value = cls.GetNameSMDet(reportes[i].smgr,"2");
                        ews.Cells["g" + (i + 3).ToString()].Value = reportes[i].prospecto;
                        ews.Cells["h" + (i + 3).ToString()].Value = reportes[i].empresa;
                        ews.Cells["i" + (i + 3).ToString()].Value = reportes[i].correo;
                        ews.Cells["j" + (i + 3).ToString()].Value = reportes[i].telefono;
                        ews.Cells["k" + (i + 3).ToString()].Value = reportes[i].etiqueta;
                        ews.Cells["l" + (i + 3).ToString()].Value = reportes[i].tipoevento;
                        ews.Cells["m" + (i + 3).ToString()].Value = reportes[i].nomevento;
                        ews.Cells["n" + (i + 3).ToString()].Value = Convert.ToDateTime(reportes[i].finicio).ToString("dd/MM/yyyy");
                        ews.Cells["o" + (i + 3).ToString()].Value = Convert.ToDateTime(reportes[i].ffin).ToString("dd/MM/yyyy");
                        ews.Cells["p" + (i + 3).ToString()].Value = reportes[i].ciaav;
                        ews.Cells["q" + (i + 3).ToString()].Value = reportes[i].lb;
                        ews.Cells["q" + (i + 3).ToString()].Style.Numberformat.Format = "0.00";
                        ews.Cells["r" + (i + 3).ToString()].Value = reportes[i].lbm;
                        ews.Cells["s" + (i + 3).ToString()].Value = reportes[i].servadic;
                        ews.Cells["t" + (i + 3).ToString()].Value = reportes[i].lpe;
                        ews.Cells["u" + (i + 3).ToString()].Value = Convert.ToDateTime(reportes[i].fpe).ToString("dd/MM/yyyy");
                        ews.Cells["v" + (i + 3).ToString()].Value = reportes[i].comentarios;
                    }
                    //termina excel
                    ReportArray = package.GetAsByteArray();
                }
                return File(ReportArray, XlsxContentType, "CaptureRatio_" + System.DateTime.Now.ToString("ddMMyyyy") + ".xlsx");
            }
            catch (Exception ex) { ViewBag.datashow = ex.Message; return View(); }
        }
        [HttpPost]
        public IActionResult CaptureRatio(NetCorePSAV.Models.NCRModel.SearchNCR nCR, string Consulta, string Exporta)
        {
            GCCorePSAV.Data.clsQuery cls = new GCCorePSAV.Data.clsQuery();
            if (!string.IsNullOrEmpty(Exporta))
            {
                return RedirectToAction("ExportCRResult", nCR);
            }
            if (Consulta.Equals("1"))
            {
                List<NetCorePSAV.Models.NCRModel.PreConsultaNCR> preConsultaNCRs = cls.GetPreConsultaNCRs(nCR);
                if (preConsultaNCRs.Count > 0)
                {
                    ViewBag.TieneFilas = true; //Location - Cascade
                    ViewBag.Locations = cls.GetNLocations();
                    //MotivoLb
                    ViewBag.LBMotivo = cls.GetMotivos();
                }
                else
                {
                    ViewBag.Locations = cls.GetNLocations();
                    //MotivoLb
                    ViewBag.LBMotivo = cls.GetMotivos();
                    ViewBag.TieneFilas = false;
                }
                ViewBag.CRResult = preConsultaNCRs;
            }
            return View(nCR);
        }
        // GET: /<controller>/
        public IActionResult CaptureRatio()
        {
            GCCorePSAV.Data.clsQuery cls = new GCCorePSAV.Data.clsQuery();
            ViewBag.TieneFilas = false;
            //Location - Cascade
            ViewBag.Locations = cls.GetNLocations();
            //MotivoLb
            ViewBag.LBMotivo = cls.GetMotivos();
            return View();
        }
        public IActionResult NewCR()
        {
            GCCorePSAV.Data.clsQuery cls = new GCCorePSAV.Data.clsQuery();
            //get all data from DB
            //DET
            ViewBag.DET = cls.GetDETs();
            //SAles Manager
            ViewBag.RepVtas = cls.RepVtas();
            //Location - Cascade
            ViewBag.Locations = cls.GetNLocations();
            ViewBag.datasourceC = cls.GetCiudades();
            ViewBag.datasourceI = cls.GetNuLocations();
            //Etiqueta
            ViewBag.Etiquetas = cls.GetEtiquetas();
            //TipoEvento
            ViewBag.TipoEvento = cls.GetTipoEventos();
            //MotivoLb
            ViewBag.LBMotivo = cls.GetMotivos();
            //Sadic
            ViewBag.sadic = cls.GetSadics();
            return View();
        }
        [HttpPost]
        public IActionResult NewCR(NetCorePSAV.Models.NCRModel.newCRView NCR,string hiddenEle)
        {
            GCCorePSAV.Data.clsQuery cls = new GCCorePSAV.Data.clsQuery();
            if (ModelState.IsValid)
            {
                NCR.sadic = hiddenEle;
                //get send items  to sum ammounts
                string[] arrayServAdic = hiddenEle.Split(',');
                double valor = 0;
                foreach(string str in arrayServAdic)
                {
                    valor = valor + cls.GetServAdicAmmount(str);
                }
                NCR.LB = valor.ToString();
                //end get items
                cls.SaveNCR(NCR);
                return RedirectToAction("CaptureRatio");
            }
            else
            {
                //get all data from DB
                //DET
                ViewBag.DET = cls.GetDETs();
                //SAles Manager
                ViewBag.RepVtas = cls.RepVtas();
                //Location - Cascade
                ViewBag.Locations = cls.GetNLocations();
                ViewBag.datasourceC = cls.GetCiudades();
                ViewBag.datasourceI = cls.GetNuLocations();
                //Etiqueta
                ViewBag.Etiquetas = cls.GetEtiquetas();
                //TipoEvento
                ViewBag.TipoEvento = cls.GetTipoEventos();
                //MotivoLb
                ViewBag.LBMotivo = cls.GetMotivos();
                //Sadic
                ViewBag.sadic = cls.GetSadics();
                return View();
            }
        }
    }
}

NetCorePSAV/Views/CRatio/CaptureRatio.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@model NetCorePSAV.Models.NCRModel.SearchNCR
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <script type="text/javascript">
        function submitFormConsult() {
            var form = document.forms['myForm'];
            // form.action = 'put your url here';
            var el = document.createElement("input");
            el.type = "hidden";
            el.name = "Consulta";
            el.value = "1";
            form.appendChild(el);
            form.submit();
        }
        function submitFormExport() {
            var form = document.forms['myForm'];
            // form.action = 'put your url here';
            var el = document.createElement("input");
            el.type = "hidden";
            el.name = "Exporta";
            el.value = "1";
            form.appendChild(el);
            form.submit();
        }
    </script>
    <br />
    <div class="row">
        <h5>Lost Business</h5>
    </div>
    <div class="row">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a asp-action="CaptureRatio" asp-controller="CRatio">Consultas</a></li>
            <li role="presentation"><a asp-action="NewCR" asp-controller="CRatio">Nuevo</a></li>
        </ul>
    </div>
    <form method="post" asp-action="CaptureRatio" asp-controller="CRatio" name="myForm">
        <div class="row">

            <table class="table table-responsive">
                <tr>
                    <td>
                        <div class="panel">
                            <div class="panel-heading"><h5>Consulta</h5></div>
                            <div class="panel-body">
                                <table cellspacing="15" class="table table-responsive" border="0">
                                    <tr>
                                        <td cellspacing="15">Fecha Inicio:&nbsp;</td>
                                        <td cellspacing="15"><input class="form-control" type="date" asp-for="finicio" /></td>
                                        <td cellspacing="15">&nbsp;</td>
                                        <td cellspacing="15">Fecha Fin:&nbsp;</td>
                                        <td cellspacing="15"><input class="form-control" type="date" asp-for="ffin" /></td>
                                        <td cellspacing="15">&nbsp;</td>
                                        <td cellspacing="15">Evento:&nbsp;</td>
                                        <td cellspacing="15"><input class="form-control" asp-for="evento" /></td>
                                    </tr>
                                    <tr>
                                        <td>Location:&nbsp;</td>
                                        <td>
                                            <select class="form-control" name="Location" asp-for="location">
                                                <option value="0">Todos</option>
                                                @foreach (var Etiquetaa in ViewBag.Locations)
                                                {
                                                    <option value="@Etiquetaa.ParentID">@Etiquetaa.Nombre</option>
                                                }
                                            </select>
                                        </td>
                                        <td>&nbsp;</td>
                                        <td>Empresa:&nbsp;</td>
                                        <td><input class="form-control" asp-for="empresa" type="text" /></td>
                                        <td>&nbsp;</td>
                                        <td>Prospecto:&nbsp;</td>
                                        <td><input class="form-control" type="text" asp-for="prospecto" /></td>
                                    </tr>
                                    <tr>
                                        <td>Motivo de Lost Business:&nbsp;</td>
                                        <td>
                                            <select class="form-control" asp-for="lbmotivo">
                                                <option value="0">Todos</option>
                                                @foreach (var Etiquetaa in ViewBag.LBMotivo)
    {
                                            <option value="@Etiquetaa.IDMLB">@Etiquetaa.Nombre</option>
}
                                            </select>
                                        </td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    <tr><td><button class=" btn btn-success" type="submit" onclick="submitFormConsult();return false">Consultar</button></td></tr>
                                </table>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
    </div>
    @if (ViewBag.TieneFilas)
    {
        <div class="row">
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>Evento</th>
                            <th>Empresa</th>
                            <th>Location</th>
                            <th>Lost Business</th>
                            <th>Motivo de Lost Business</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var cra in ViewBag.CRResult)
                        {
                            <tr>
                                <td>@cra.Evento</td>
                                <td>@cra.Empresa</td>
                                <td>@cra.Location</td>
                                <td>@cra.LB</td>
                                <td>@cra.LBMotivo</td>
                            </tr>
                        }
                        <tr>
                            <td><button type="submit" class="btn btn-success" onclick="submitFormExport();return false">Exportar</button></td>
                        </tr>
                    </tbody>
                </table>

        </div>
    }
    </form>
}

NetCorePSAV/Views/CRatio/NewCR.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using GCCorePSAV.Models
@using GCCorePSAV.Controllers.Services
@model NetCorePSAV.Models.NCRModel.newCRView
@inject LoggedInComponent Lgc
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@await Lgc.IsAuth(HttpContextAccessor.HttpContext.Request.Cookies["Bearer"], HttpContextAccessor.HttpContext.Request.Cookies["pandoraRules"])
@if (Lgc.isAuth)
{
    <form method="post" asp-controller="CRatio" asp-action="NewCR">
        <div class="row"><h5>Nuevo Lost Business</h5></div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">
            <div class="col-lg-12">                
                <table width="100%">
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="DET" class="control-label"></label>
                                <select asp-for="DET" class="form-control">
                                    <option value="0">Seleccionar</option>
                                    @foreach (var pmgr in ViewBag.DET)
                    {
                        <option value="@pmgr.IDDet">@pmgr.Nombre</option>
    }
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="SMgr" class="control-label"></label>
                                <select asp-for="SMgr" class="form-control">
                                    <option value="0">Seleccionar</option>
                                    @foreach (var pmgr in ViewBag.RepVtas)
                    {
                        <option value="@pmgr.IDRepVtas">@pmgr.NombreCompleto</option>
    }
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <span class="bold"><b>Ciudad</b></span>
                                <ej-drop-down-list id="NLocation" datasource="ViewBag.datasourceC" watermark-text="Seleccione Ciudad" cascade-to="NuLocation" width="75%">
                                    <e-drop-down-list-fields text="Nombre" id="ParentID" value="ParentID" />
                                </ej-drop-down-list>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <span class="bold"><b>Location</b></span>
                                <ej-drop-down-list id="NuLocation" datasource="ViewBag.datasourceI" watermark-text="Seleccione Location" width="75%">
                                    <e-drop-down-list-fields text="Nombre" id="ID" value="ID" />
                                </ej-drop-down-list>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="prospecto" class="control-label"></label><input asp-for="prospecto" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="empresa" class="control-label"></label><input asp-for="empresa" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="correo" class="control-label"></label><input asp-for="correo" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="telefono" class="control-label"></label><input asp-for="telefono" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="etiqueta" class="control-label"></label>
                                <select asp-for="etiqueta" class="form-control">
                                    @foreach (var Etiquetaa in ViewBag.Etiquetas)
                    {
                        <option value="@Etiquetaa.IDEtiqueta">@Etiquetaa.Nombre</option>
    }
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="tipoevento" class="control-label"></label>
                                <select asp-for="tipoevento" class="form-control">
                                    @foreach (var Etiquetaa in ViewBag.TipoEvento)
                    {
                        <option value="@Etiquetaa.IDTipoEvento">@Etiquetaa.Nombre</option>
    }
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="nombreevento" class="control-label"></label><input asp-for="nombreevento" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="fechainicio" class="control-label"></label><input asp-for="fechainicio" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="fechafin" class="control-label"></label><input asp-for="fechafin" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="AV" class="control-label"></label><input asp-for="AV" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%">@*<div class="form-group"><label asp-for="LB" class="control-label"></label><input asp-for="LB" class="form-control" /></div>*@</td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="LBMotivo" class="control-label"></label>
                                <select asp-for="LBMotivo" class="form-control">
                                    @foreach (var Etiquetaa in ViewBag.LBMotivo)
                    {
                        <option value="@Etiquetaa.IDMLB">@Etiquetaa.Nombre</option>
    }
                                </select>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">@*<div class="form-group"><label asp-for="servadic" class="control-label"></label><select asp-for="servadic" class="form-control" onchange="doenable();"><option value="0">NO</option><option value="1">SI</option></select></div>*@&nbsp;</td>
                    </tr>
                    <tr>
                        <td width="50%">
                            <div class="form-group">
                                <label asp-for="sadic" class="control-label"></label>
                                <ej-drop-down-list id="sadic" datasource="ViewBag.sadic" show-checkbox="true" width="50%" multi-select-mode="@MultiSelectModeTypes.VisualMode">
                                    <e-drop-down-list-fields text="Nombre" value="Nombre" />
                                </ej-drop-down-list>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="lpe" class="control-label"></label><input asp-for="lpe" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="5%"><div class="form-group"><label asp-for="fpe" class="control-label"></label><input asp-for="fpe" class="form-control" /></div></td>
                    </tr>
                    <tr>
                        <td width="50%"><div class="form-group"><label asp-for="comments" class="control-label"></label><textarea asp-for="comments" class="form-control"></textarea></div></td>
                        <td width="50%">&nbsp;</td>
                    </tr>
                    <tr>
                        <td><button type="submit" class="btn btn-success">Guardar</button></td>
                        <td><button type="reset" class="btn btn-warning">Cancelar</button></td>
                    </tr>
                </table>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        function doenable() {
            var siono = $("servadic option:selected").val();
            if (siono == '1') { $('#sadic').removeAttr('disabled'); } else { $('#sadic').attr('disabled', 'disabled'); }
        }
    </script>
    @section Scripts {
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    }
}